version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - mern_network
    environment:
      REACT_APP_API_URL: http://backend:5050

  backend:
    build: 
      context: ./backend
    ports:
      - "5050:5050"
    networks:
      - mern_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db

networks:
  mern_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
